trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'
  project: 'Veracode.OSS.Wrapper/Veracode.OSS.Wrapper.csproj'

steps:

- task: DotNetCoreCLI@2
  displayName: 'dotnet build and pack'
  inputs:
    command: 'build'
    arguments: '--configuration $(buildConfiguration)'
    projects: '$(project)'
    
- task: CopyFiles@2
  displayName: "Copy to Staging"
  inputs:
    sourceFolder: '$(Build.SourcesDirectory)/Veracode.OSS.Wrapper/bin/Release/'
    contents: '*.nupkg' 
    targetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  displayName: "Publish drop to Azure Devops"
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: drop

- task: NuGetCommand@2
  displayName: 'Publish drop to NuGet'
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg;!$(Build.ArtifactStagingDirectory)/*.symbols.nupkg'
    nuGetFeedType: 'external'
    publishFeedCredentials: 'nuget live'