trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'
  project: 'VeracodeServicesCore/VeracodeService/VeracodeService.csproj'

steps:

- task: DotNetCoreCLI@2
  displayName: 'dotnet build and pack'
  inputs:
    command: 'build'
    arguments: '--configuration $(buildConfiguration)'
    projects: '$(project)'
    
- task: CopyFiles@2
  displayName: "Copy to Staging"
  inputs:
    sourceFolder: '$(Build.SourcesDirectory)/VeracodeServicesCore/VeracodeService/bin/Release/'
    contents: '*.nupkg' 
    targetFolder: '$(Build.ArtifactStagingDirectory)'

- task: Veracode@3
  displayName: "Veracode scan"
  inputs:
    ConnectionDetailsSelection: 'Credentials'
    apiId: '$(VeracodeApiId)'
    apiKey: '$(VeracodeApiKey)'
    veracodeAppProfile: '$(system.teamProject)'
    version: '$(build.buildNumber)'
    filepath: '$(build.artifactstagingdirectory)'
    createSandBox: false
    createProfile: true
    failTheBuildIfVeracodeScanDidNotInitiate: true
    scanStatusCheckInterval: '60'
    importResults: true
    failBuildOnPolicyFail: true

- task: PublishBuildArtifacts@1
  displayName: "Publish drop to Azure Devops"
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: drop

- task: NuGetCommand@2
  displayName: 'Publish drop to NuGet'
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg;!$(Build.ArtifactStagingDirectory)/*.symbols.nupkg'
    nuGetFeedType: 'external'
    publishFeedCredentials: 'nuget live'